In [1]:
#install all libraries
!pip install emot
!pip install emoji
!pip install demoji
!pip install punct
!pip install contractions

ERROR: Could not find a version that satisfies the requirement punct (from versions: none)
ERROR: No matching distribution found for punct


In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
import pandas as pd

In [5]:
nltk.download('omw-1.4')
pd.set_option("max_colwidth" ,220)
wn = nltk.WordNetLemmatizer()
nltk.download('wordnet')

nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
#from textblob import TextBlob
import emoji
import nltk.data
import numpy as np
import re
import time
import string
import emoji
import demoji
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.corpus import stopwords
import string
import contractions
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import re
from nltk.tokenize import TweetTokenizer
import regex
import nltk
from nltk.stem import SnowballStemmer
demoji.download_codes()
lemmatizer = WordNetLemmatizer()
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report,accuracy_score
from sklearn.svm import LinearSVC

C:\Users\User\AppData\Local\Temp/ipykernel_13604/2799970465.py:23: FutureWarning: The demoji.download_codes attribute is deprecated and will be removed from demoji in a future version. It is an unused attribute as emoji codes are now distributed directly with the demoji package.
  demoji.download_codes()


In [10]:
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
#import xgboost as xgb
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

In [11]:
#read the dataset
df_train=pd.read_csv('Fake_train.csv')
df_dev=pd.read_csv('Fake_dev.csv')
#df_test=pd.read_csv('/content/drive/MyDrive/AI ML/Fake_test_without_labels.csv', sep='\t')

In [12]:
df_train

text  \
0                                                                                  നല്ല അവതരണം. സത്യം പുറത്തു വരട്ടെ   
1                                                                                                        Masha Allah   
2     അന്വേഷണം കഴിയുമ്പോൾ,. C. A. A. യ്ക്ക് എതിരായ കലാപം പോലെ ആകുമോ.. സ്വന്തം ആളെ തന്നെ പിടിച്ചു അകത്തിടേണ്ടി വരുമോ?   
3                                                                    Illathentha avaru purath vidayittalland verenth   
4                                                            Barana pakshathin matoru niyamam.nalla moyanth manthrii   
...                                                                                                              ...   
3252        വീണാ ജോർജ് എന്ന ഒരു ആരോഗ്യ മന്ത്രി വന്നതിനു ശേഷം  കേരളത്തിന്റെ ആരോഗ്യ സ്ഥിതി വളരെ മോശവും പ്രഹസനവുമാണ്...   
3253                                                                                              ഇതാണ് പിണുവാതിര😂😂😂   
3254                                                                                                കേസ് എടുക്കണം 💯👍   
3255                                                                   എല്ലാത്തിനേം 501 സോപ്പിട്ട് കളിപ്പിച്ച് വിടണം   
3256                                               Day by day leaders r acting like a fool in devil&#39;s on country   

         label  
0         Fake  
1         Fake  
2         Fake  
3         Fake  
4     original  
...        ...  
3252  original  
3253  original  
3254  original  
3255  original  
3256  original  

[3257 rows x 2 columns]

In [13]:
df_dev

text  \
0                                                                                                                                                                                                     Full.  Musilm.   Verodamum   
1    പക്ഷികളും മൃഗങ്ങളും ഈ ലോകത്ത് സുഖമായി ജീവിക്കുന്നു വിവരവും വിദ്യാഭ്യാസവും ഉണ്ട് എന്ന് പറയുന്ന മനുഷ്യർ മരമണ്ടൻ മാരായി ജീവിക്കുന്നു മോഹനൻ വൈദ്യരും ജേക്കബ് വടക്കഞ്ചേരി യും പറയുന്ന തലങ്ങളിലേക്ക് നിങ്ങൾ എത്താതെ തന്നെ അവരെ...   
2                                                                                                                    ഒരു താടിക്കാരൻ പാത്രം കൊട്ടാൻ പറഞ്ഞപ്പോ ........ മറ്റൊരു ഒന്നും ഇല്ലാത്തവൻ കൈ കൊട്ടാൻ പറയുന്നു ....... 😭😭😭😭   
3                                                                                                                                                                                                              കുംഭളേമ<br>മറന്നോ   
4                                                                                                                                                                      ഇത് തിരുവാതിര അല്ല...... കോറോണയെ കൈകൊട്ടി കൊല്ലുകയാണ് 😂😂😂   
..                                                                                                                                                                                                                           ...   
810                                                                                                                                                                                       ജനങ്ങൾ വിഡ്ഢികളല്ല .. അത്രേ പറയാനുള്ളു   
811                                                                                                                                                                                                                😂😂ഒരു പിണറായി   
812                                                                Mr sir are you know about bodhidarma the great sindha not a English doctor first you understand  our nature and natural medicine ok then you talk and comment   
813                                                                                                                                                                                                  ബുദ്ധിയുള്ളവരെ  വിജയിപ്പിക്   
814                                                                                                                                                                                      വേണ്ടാത്ത പരിപാടിയിപ്പോയി എന്തായാലും...   

        label  
0        Fake  
1        Fake  
2    original  
3    original  
4    original  
..        ...  
810  original  
811  original  
812      Fake  
813      Fake  
814  original  

[815 rows x 2 columns]

In [16]:
df_train['label'].value_counts()


original    1658
Fake        1599
Name: label, dtype: int64

In [15]:
df_dev['label'].value_counts()

original    409
Fake        406
Name: label, dtype: int64

In [17]:
#emot_object = emot.core.emot()        #PREPROCESSING
ps =PorterStemmer()
lemmatiser = WordNetLemmatizer()
english_stopwords = stopwords.words('english')
exclude = set(string.punctuation)
def preprocess(text):
  #text=demoji.findall(df['Text'])
  text = contractions.fix(text.lower(), slang=True)
  text =re.sub("@ ?[A-Za-z0-9_]+", "", text)
  text= re.sub(r'\d+', '', text)
  text=re.sub(r'$', '', text)
  text= re.sub(r'’','', text )
  text=re.sub('<.*?>','',text)
  text=re.sub(r'http\S+', '', text)
  #text=emoji.demojize(text, delimiters=(" ", " "))
  text = ''.join(ch for ch in text if ch not in exclude)
  tokens = word_tokenize(text)
  #print("Tokens:", tokens)
  text = [t for t in tokens if t not in english_stopwords]
  text = " ".join(text)
  return text

In [18]:
import emoji
#import demoji
#demoji.download_codes()
def emo(text):
  temp=emoji.demojize(text,delimiters=(" "," "))
  temp=temp.replace("_","  ")
  return temp

In [24]:
df_train['clean_text']=df_train["text"].apply(lambda x:emo(x))
df_train["clean_text"]=df_train['clean_text'].apply(lambda X: preprocess(X))

In [20]:
df_train

text  \
0                                                                                  നല്ല അവതരണം. സത്യം പുറത്തു വരട്ടെ   
1                                                                                                        Masha Allah   
2     അന്വേഷണം കഴിയുമ്പോൾ,. C. A. A. യ്ക്ക് എതിരായ കലാപം പോലെ ആകുമോ.. സ്വന്തം ആളെ തന്നെ പിടിച്ചു അകത്തിടേണ്ടി വരുമോ?   
3                                                                    Illathentha avaru purath vidayittalland verenth   
4                                                            Barana pakshathin matoru niyamam.nalla moyanth manthrii   
...                                                                                                              ...   
3252        വീണാ ജോർജ് എന്ന ഒരു ആരോഗ്യ മന്ത്രി വന്നതിനു ശേഷം  കേരളത്തിന്റെ ആരോഗ്യ സ്ഥിതി വളരെ മോശവും പ്രഹസനവുമാണ്...   
3253                                                                                              ഇതാണ് പിണുവാതിര😂😂😂   
3254                                                                                                കേസ് എടുക്കണം 💯👍   
3255                                                                   എല്ലാത്തിനേം 501 സോപ്പിട്ട് കളിപ്പിച്ച് വിടണം   
3256                                               Day by day leaders r acting like a fool in devil&#39;s on country   

         label  \
0         Fake   
1         Fake   
2         Fake   
3         Fake   
4     original   
...        ...   
3252  original   
3253  original   
3254  original   
3255  original   
3256  original   

                                                                                                clean_text  
0                                                                         നല്ല അവതരണം സത്യം പുറത്തു വരട്ടെ  
1                                                                                              masha allah  
2       അന്വേഷണം കഴിയുമ്പോൾ c യ്ക്ക് എതിരായ കലാപം പോലെ ആകുമോ സ്വന്തം ആളെ തന്നെ പിടിച്ചു അകത്തിടേണ്ടി വരുമോ  
3                                                          illathentha avaru purath vidayittalland verenth  
4                                                   barana pakshathin matoru niyamamnalla moyanth manthrii  
...                                                                                                    ...  
3252  വീണാ ജോർജ് എന്ന ഒരു ആരോഗ്യ മന്ത്രി വന്നതിനു ശേഷം കേരളത്തിന്റെ ആരോഗ്യ സ്ഥിതി വളരെ മോശവും പ്രഹസനവുമാണ്  
3253                                          ഇതാണ് പിണുവാതിര face tears joy face tears joy face tears joy  
3254                                                                   കേസ് എടുക്കണം hundred points thumbs  
3255                                                             എല്ലാത്തിനേം സോപ്പിട്ട് കളിപ്പിച്ച് വിടണം  
3256                                                     day day leaders r acting like fool devils country  

[3257 rows x 3 columns]

In [25]:
df_dev['clean_text']=df_dev["text"].apply(lambda x:emo(x))
df_dev["clean_text"]=df_dev['clean_text'].apply(lambda X: preprocess(X))

In [26]:
df_dev

text  \
0                                                                                                                                                                                                     Full.  Musilm.   Verodamum   
1    പക്ഷികളും മൃഗങ്ങളും ഈ ലോകത്ത് സുഖമായി ജീവിക്കുന്നു വിവരവും വിദ്യാഭ്യാസവും ഉണ്ട് എന്ന് പറയുന്ന മനുഷ്യർ മരമണ്ടൻ മാരായി ജീവിക്കുന്നു മോഹനൻ വൈദ്യരും ജേക്കബ് വടക്കഞ്ചേരി യും പറയുന്ന തലങ്ങളിലേക്ക് നിങ്ങൾ എത്താതെ തന്നെ അവരെ...   
2                                                                                                                    ഒരു താടിക്കാരൻ പാത്രം കൊട്ടാൻ പറഞ്ഞപ്പോ ........ മറ്റൊരു ഒന്നും ഇല്ലാത്തവൻ കൈ കൊട്ടാൻ പറയുന്നു ....... 😭😭😭😭   
3                                                                                                                                                                                                              കുംഭളേമ<br>മറന്നോ   
4                                                                                                                                                                      ഇത് തിരുവാതിര അല്ല...... കോറോണയെ കൈകൊട്ടി കൊല്ലുകയാണ് 😂😂😂   
..                                                                                                                                                                                                                           ...   
810                                                                                                                                                                                       ജനങ്ങൾ വിഡ്ഢികളല്ല .. അത്രേ പറയാനുള്ളു   
811                                                                                                                                                                                                                😂😂ഒരു പിണറായി   
812                                                                Mr sir are you know about bodhidarma the great sindha not a English doctor first you understand  our nature and natural medicine ok then you talk and comment   
813                                                                                                                                                                                                  ബുദ്ധിയുള്ളവരെ  വിജയിപ്പിക്   
814                                                                                                                                                                                      വേണ്ടാത്ത പരിപാടിയിപ്പോയി എന്തായാലും...   

        label  \
0        Fake   
1        Fake   
2    original   
3    original   
4    original   
..        ...   
810  original   
811  original   
812      Fake   
813      Fake   
814  original   

                                                                                                                                                                                                                      clean_text  
0                                                                                                                                                                                                          full musilm verodamum  
1    പക്ഷികളും മൃഗങ്ങളും ഈ ലോകത്ത് സുഖമായി ജീവിക്കുന്നു വിവരവും വിദ്യാഭ്യാസവും ഉണ്ട് എന്ന് പറയുന്ന മനുഷ്യർ മരമണ്ടൻ മാരായി ജീവിക്കുന്നു മോഹനൻ വൈദ്യരും ജേക്കബ് വടക്കഞ്ചേരി യും പറയുന്ന തലങ്ങളിലേക്ക് നിങ്ങൾ എത്താതെ തന്നെ അവരെ...  
2                                                              ഒരു താടിക്കാരൻ പാത്രം കൊട്ടാൻ പറഞ്ഞപ്പോ മറ്റൊരു ഒന്നും ഇല്ലാത്തവൻ കൈ കൊട്ടാൻ പറയുന്നു loudly crying face loudly crying face loudly crying face loudly crying face  
3                                                                                                                                                                                                                  കുംഭളേമമറന്നോ  
4                                                                                                                                   ഇത് തിരുവാത

In [30]:
#Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
bow_representation = vectorizer.fit_transform(df_train['clean_text'])

In [31]:
#matrics representation
print('\nBag of Words Representation:')
print(bow_representation.toarray())


Bag of Words Representation:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
print('\nBag of Words Representation:')
print(bow_representation)


Bag of Words Representation:
  (0, 7480)	1
  (0, 6595)	1
  (0, 8236)	1
  (0, 7930)	1
  (0, 8114)	1
  (1, 3453)	1
  (1, 286)	1
  (2, 6553)	1
  (2, 8198)	1
  (2, 6994)	1
  (2, 6822)	1
  (2, 6981)	1
  (2, 6632)	1
  (2, 8096)	1
  (2, 6665)	1
  (2, 7325)	1
  (2, 6527)	1
  (2, 8111)	1
  (3, 2239)	1
  (3, 648)	1
  (3, 4836)	1
  (3, 6273)	1
  (3, 6255)	1
  (4, 758)	1
  (4, 4202)	1
  :	:
  (3252, 8129)	1
  (3252, 7879)	1
  (3252, 7695)	1
  (3252, 8185)	1
  (3252, 8345)	1
  (3252, 7913)	1
  (3253, 1916)	3
  (3253, 5573)	3
  (3253, 2550)	3
  (3253, 6706)	1
  (3254, 6929)	1
  (3254, 6818)	1
  (3254, 5806)	1
  (3254, 2194)	1
  (3254, 4566)	1
  (3255, 6988)	1
  (3255, 6835)	1
  (3255, 7214)	1
  (3256, 3180)	1
  (3256, 3154)	1
  (3256, 1405)	2
  (3256, 1319)	1
  (3256, 1986)	1
  (3256, 1450)	1
  (3256, 135)	1


In [34]:
#feature extraction
#with parameters

tf_idf = TfidfVectorizer(max_features=5000)
#applying tf idf to training data
X_train_tf1 = tf_idf.fit_transform(df_train['clean_text'])
#transforming test data into tf-idf matrix
X_dev_tf1 = tf_idf.transform(df_dev["clean_text"])
#applying tf idf to training data
#X_train_tf1 = tf_idf.transform(df_train['clean_text'])

In [35]:
#MNB CLASSIFIER
from sklearn.naive_bayes import MultinomialNB
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf1, df_train['label'])

MultinomialNB()

In [36]:
NB_pred1 = naive_bayes_classifier.predict(X_dev_tf1)
print(classification_report(df_dev['label'], NB_pred1))

              precision    recall  f1-score   support

        Fake       0.82      0.79      0.81       406
    original       0.80      0.83      0.82       409

    accuracy                           0.81       815
   macro avg       0.81      0.81      0.81       815
weighted avg       0.81      0.81      0.81       815



In [38]:
#Gaussian Naive Bayes CLassifier
x_traintf=X_train_tf1.toarray()
x_testtf=X_dev_tf1.toarray()

In [39]:
nb = GaussianNB()
nb.fit(x_traintf, df_train['label'])
GBN_pred = nb.predict(x_testtf)
print(classification_report(df_dev['label'], GBN_pred))

              precision    recall  f1-score   support

        Fake       0.77      0.53      0.63       406
    original       0.64      0.85      0.73       409

    accuracy                           0.69       815
   macro avg       0.71      0.69      0.68       815
weighted avg       0.71      0.69      0.68       815



In [45]:
#feature extraction
#without parameters

tf_idf1 = TfidfVectorizer()
#applying tf idf to training data
X_train_tf2 = tf_idf1.fit_transform(df_train['clean_text'])
#transforming test data into tf-idf matrix
X_dev_tf2 = tf_idf1.transform(df_dev["clean_text"])
#applying tf idf to training data
#X_train_tf1 = tf_idf.transform(df_train['clean_text'])

In [46]:
#MNB CLASSIFIER (without parameters)
from sklearn.naive_bayes import MultinomialNB
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf2, df_train['label'])

MultinomialNB()

In [47]:
NB_pred2 = naive_bayes_classifier.predict(X_dev_tf2)
print(classification_report(df_dev['label'], NB_pred2))

              precision    recall  f1-score   support

        Fake       0.81      0.79      0.80       406
    original       0.80      0.82      0.81       409

    accuracy                           0.81       815
   macro avg       0.81      0.81      0.81       815
weighted avg       0.81      0.81      0.81       815



In [48]:
#Gaussian Naive Bayes CLassifier(without parameters)
x_traintff=X_train_tf2.toarray()
x_testtff=X_dev_tf2.toarray()

In [49]:
nb1= GaussianNB()
nb1.fit(x_traintff, df_train['label'])
GBN_pred1 = nb1.predict(x_testtff)
print(classification_report(df_dev['label'], GBN_pred1))

              precision    recall  f1-score   support

        Fake       0.74      0.51      0.61       406
    original       0.63      0.82      0.71       409

    accuracy                           0.67       815
   macro avg       0.68      0.67      0.66       815
weighted avg       0.68      0.67      0.66       815



In [51]:
#feature extraction
#with many parameters

tf_idf2 = TfidfVectorizer(analyzer='word', stop_words=None,ngram_range=(1, 1),max_features=5000)
#applying tf idf to training data
X_train_tf3= tf_idf2.fit_transform(df_train['clean_text'])
#transforming test data into tf-idf matrix
X_dev_tf3= tf_idf2.transform(df_dev["clean_text"])
#applying tf idf to training data
#X_train_tf1 = tf_idf.transform(df_train['clean_text'])

In [52]:
#MNB CLASSIFIER (with many parameters)
from sklearn.naive_bayes import MultinomialNB
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf3, df_train['label'])

MultinomialNB()

In [53]:
NB_pred3 = naive_bayes_classifier.predict(X_dev_tf3)
print(classification_report(df_dev['label'], NB_pred3))

              precision    recall  f1-score   support

        Fake       0.82      0.79      0.81       406
    original       0.80      0.83      0.82       409

    accuracy                           0.81       815
   macro avg       0.81      0.81      0.81       815
weighted avg       0.81      0.81      0.81       815



In [55]:
#Gaussian Naive Bayes CLassifier(with many parameters)
x_traintfff=X_train_tf3.toarray()
x_testtfff=X_dev_tf3.toarray()

In [56]:
nb2= GaussianNB()
nb2.fit(x_traintfff, df_train['label'])
GBN_pred2= nb2.predict(x_testtfff)
print(classification_report(df_dev['label'], GBN_pred2))

              precision    recall  f1-score   support

        Fake       0.77      0.53      0.63       406
    original       0.64      0.85      0.73       409

    accuracy                           0.69       815
   macro avg       0.71      0.69      0.68       815
weighted avg       0.71      0.69      0.68       815

